# Generated by Django 6.0.1 on 2026-05-12 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="recipients",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
