ROOM_MESSAGE_SEND = 'MESSAGE_SEND'
ROOM_MESSAGE_UPDATED = 'MESSAGE_UPDATED'
ROOM_MESSAGE_DELETED = 'MESSAGE_DELETED'

ROOM_CREATED = 'ROOM_CREATED'
ROOM_UPDATED = 'ROOM_UPDATED'
ROOM_DELETED = 'ROOM_DELETED'