ROOM_MESSAGE_SEND = "MESSAGE_SEND"
ROOM_MESSAGE_UPDATED = "MESSAGE_UPDATED"
ROOM_MESSAGE_DELETED = "MESSAGE_DELETED"

ROOM_CREATED = "ROOM_CREATED"
ROOM_UPDATED = "ROOM_UPDATED"
ROOM_DELETED = "ROOM_DELETED"

USER_SERVER_JOINED = "SERVER_JOINED"
USER_SERVER_LEFT = "SERVER_LEFT"

USER_UPDATED = "USER_UPDATED"

SERVER_MEMBER_JOINED = "MEMBER_JOINED"
SERVER_MEMBER_LEFT = "MEMBER_LEFT"
