# Generated by Django 6.0.1 on 2026-02-07 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0002_servermember"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="servermember",
            constraint=models.UniqueConstraint(
                fields=("user", "server"), name="unique_user_per_server"
            ),
        ),
    ]
